output:
  format: "json" # Maybe add option for pickle?
  dir: "./output/"
  file: "output-{concurrency:03d}.json"
storage: # TODO
  type: local
dataset:
  file: "datasets/ems.jsonl"
  max_queries: 1000
  min_input_tokens: 0
  max_input_tokens: 1024
  min_output_tokens: 0
  max_output_tokens: 1024
  max_sequence_tokens: 2048 # system_prompt tokens not counted towards filters
  custom_prompt_format: null # Sample : "{system_prompt}\n\n{prompt}""
load_options:
  type: constant #Future options: loadgen, stair-step
  concurrency: 1000 # concurrency of requests by user
  duration: 20 # In seconds. Maybe in future support "100s" "10m", etc...
plugin: "ems_plugin"
plugin_options:
  host: "localhost:8080"
  endpoint: "/predictions/model"
extra_metadata:
  replicas: 1
